name: Compose Deploy
on: 
  push:
    paths:
      - './docker-compose.yml'

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
  
  deploy-compose:
    needs: build-and-push-client-image
    runs-on: ubuntu-latest
    steps:
    - name: SSH connection
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: 22
        script: |
          cd app/WebManager
          docker-compose stop
          git pull origin prod