name: Test SSH Connection

on:
  workflow_dispatch:

jobs:
  ssh-test:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into server and test connection
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            echo "Connected successfully!"
            whoami