name: Up Containers

on:
  workflow_run:
    workflows: ["Client Deploy", "Server Deploy"]
    types:
      - completed

jobs:
  run-compose:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: SSH connection
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: 22
        script: |
          cd app/WebManager
          docker-compose up -d